
<style>
   body{
       background-color:#000;
   }
   .left_page{
        background-image: linear-gradient(to top,
            #de5b89,#2696E8);
            height:100vh;
}
</style>
<div class="container-fluid  main">
   <div class="">
       <div class="row">
        <div class="col-lg-5 py-5  text-center left_page">
                <h1 class="mb-5 text-white mx-0">BIZO</h1>
                <p class="py-5 mt-5 text-white fw-bolder" style="font-size:50px;">You’re in! Get ready <br> for it.</p>
        </div>
        <div  class="col-lg-7 mt-5 py-5 text-white fw-bolder">
            <div class="py-5 mt-5 mx-5">
               <p style="font-size:25px;text-align:justify;"> Thanks for signing up—there's just one last thing to do.<br> Verify your email address by clicking the link <br> in your confirmation email.
               </p>
               <hr> 
               <div class=" text-muted">
                    <a href="../../Social Media/">Go Back Home.</a>  
               </div>
           </div>
        </div>
        </div>
   </div>
</div>
