<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../assets/css/style.css">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
      <link rel="icon" href="../../assets/image/logo_final.png" type="image/x-icon">
      <link href="../../assets/vendor/aos/aos.css" rel="stylesheet">
      <link href="../../assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
      <link href="../../assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
      <link href="../../assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
      <link href="../../assets/vendor/remixicon/remixicon.css" rel="stylesheet">
      <link href="../../assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
      <title><?=$page_titel?></title>
      <style>
         body{
          background-color: whitesmoke;
         }
      </style>
    </head>
<body>

    <?php include $template.".phtml"; ?>

</body>
</html>

