
<style>
    img{
        width:100%;
        height:100%;
    }
</style>
<div class="d-flex container  justify-content-center align-items-center py-5 mt-5">
    <div class="col-xl-8 rounded shadow-lg">
        <div class="row">
            <div class="col-md-6">
                 <lottie-player src="https://assets1.lottiefiles.com/packages/lf20_dd9wpbrh.json"   speed="1"  style="width: 100%; height: 100%;"  loop  autoplay></lottie-player>
            </div>
            <div class="col-md-6 ">
    <form  class="py-5 mt-5 text-center" action="index.php" method="POST">
    <h1>Renvoyer Email</h1>
        <?php if(array_key_exists('msg',$_GET)): ?>
                <div class="alert alert-danger">
                    <?=$_GET['msg']?>
                </div>
        <?php endif;?>
          <input type="email" class="form-control mb-2" name="email" placeholder="user@gmail.com">
          <button name="submit" class="btn btn-outline-success mb-2">Renvoyer</button>
          <div class="text-center">
          <a href="../login/"><button  class="btn btn-secondary">cancel</button> </a>
      </div>
    </form>
    
    </div>
    </div>
    </div>
</div>