
<canvas style="position:absolute;width:70%" class="text-center" id="my-canvas"></canvas>
<div  class="content_overview">
<div class="row px-4  py-5 mt-5">
    <h1 class="text-center mb-4">Review :</h1>
     <div class="col-md-4 mb-4 ">
        <div class="card border-left-red shadow  py-2">
                  <div class="card-body">
                         <div class="row align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                   nombre of all Users </div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800"><?=$number_all_user?></div>
                                </div>
                                 <div class="col-auto">
                                       <i class="fa-solid fa-2x fa-user text-gray-300"></i>
                                  </div>
                            </div>
                     </div>
          </div>
     </div>

     <div class="col-md-4  mb-4 ">
        <div class="card border-left-primary shadow  py-2">
                  <div class="card-body">
                         <div class="row no-gutters align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                   nombre of All Pub</div>
                                   <div class="h5 mb-0 font-weight-bold "><?=$number_all_pub?></div>
                                </div>
                                 <div class="col-auto">
                                       <i class="fa-solid fa-2x  fa-film"></i>
                                  </div>
                            </div>
                     </div>
          </div>
     </div>
  

     <div class="col-md-4 mb-4 ">
        <div class="card border-left-primary shadow  py-2">
                  <div class="card-body">
                         <div class="row no-gutters align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                   nombre of Story</div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800"><?=$number_all_story?></div>
                                </div>
                                 <div class="col-auto">
                                    <i class="fa-solid fa-2x fa-photo-film"></i>
                                  </div>
                            </div>
                     </div>
          </div>
      </div>

      <div class="col-md-4 mb-4 ">
        <div class="card border-left-primary shadow  py-2">
                  <div class="card-body">
                         <div class="row no-gutters align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                   nombre of liked</div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800"><?=$nbr_liked?></div>
                                </div>
                                 <div class="col-auto">
                                    <i class="fa-solid fa-2x fa-thumbs-up"></i>
                                  </div>
                            </div>
                     </div>
          </div>
      </div>


      
      <div class="col-md-4 mb-4 ">
        <div class="card border-left-primary shadow py-2">
                  <div class="card-body">
                         <div class="row no-gutters align-items-center">
                               <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                   nombre of comment</div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800"><?=$nbr_comment?></div>
                                </div>
                                 <div class="col-auto">
                                    <i class="fa-solid fa-2x fa-comment"></i>
                                  </div>
                            </div>
                     </div>
          </div>
      </div>
    </div>
  <script src="../assets/js/index.min.js"></script>
<script>
   var confettiSettings = { target: 'my-canvas' };
   var confetti = new ConfettiGenerator(confettiSettings);
   confetti.render();
</script>