
<style>
    img{
        width: 100%;
        height: 100%;
    }
</style>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div class="container d-flex justify-content-center align-items-center">
<div class="row shadow-lg mt-5">
     <div class="col-md-6 py-5 mt-4">
            <form action="index.php" method="post">
                 <h1 class="text-center mb-5">Reset Password</h1>
                  <?php if(array_key_exists('msg',$_GET)): ?>
                     <div class="alert alert-danger"> 
                        <?=$_GET['msg']?>
                     </div>
                  <?php endif;?>
                  <input type="email" class="form-control mb-4 mt-4" name="email" placeholder="Entrer votre email">
                 
                  <div class="text-center mb-2">
                          <div class="g-recaptcha text-center" data-sitekey="6Ldl-BUjAAAAAFdE1e3w9KBQLPoPwBJWBWlCT7GE"></div>
                  </div>

                  <div class="text-center mb-4">
                        <button name="suivant" class="btn btn-success">Suivant</button>
                  </div>
            </form>
                 <div class="text-center">
                       <a href="../login/"><button  class="btn btn-secondary">cancel</button> </a>
                  </div>
     </div>
     <div class="col-md-6 ">
            <img src="../../assets/image/63004-profile-password-unlock.gif" alt="">
     </div>
</div>
</div>
<script type="text/javascript">
  var onloadCallback = function() {
    alert("grecaptcha is ready!");
  };
</script>







