
  <div class="container">
      <div class="d-flex justify-content-center">
        <div>
             <img class="rounded-pill" width="150px" height="150px" src="..<?=userFromId($id)['photo_user']?>" alt="">
             <h3 class="text-center mt-2" id="text"><?=userFromId($id)['name']?></h3>
        </div>
     </div>
<ul class="nav nav-tabs " id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">List Amis</button>
  </li>
 
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Info Personnel</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active mb-5" id="home" role="tabpanel" aria-labelledby="home-tab">
      <p class="text-center mt-3" id="text">Num Ami <?=$count?></p>
      <div>
        <div class="row gap-5">
        <?php if($all_friends=='vide'): ?>
         <div class="alert alert-danger">
               No User FOUND
         </div>
      <?php else: ?>
            <?php foreach($all_friends as $value): ?>
                <div class="card card_pub col-lg-4" style="width:8rem;">
                   <img src="..<?=$value['photo_user']?>" class="card-img-top" alt="...">
                   <div class="card-body">
                     <p class="card-text" id="text"><?=$value['name']?></p>
                    </div>
               </div>
            <?php endforeach; ?>
            <?php endif; ?>
            </div>
      </div>
  </div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
        <p id="text" class="text-center mt-2">Information :</p>
        <div class="p-3" id="text">
             Date Created :<?=userFromId($id)['date_created']?> <br>
             Email :<?=userFromId($id)['email']?>
        </div>
  </div>
</div>
</div>