       
        <div class="all_story">
       
          <div class="story-container">
                     <div class="content-add">
                         <div class="img-container">
                                <img type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" src="../assets/image/add.png" width="70px" height="70px" alt="">
                         </div>
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Add Story</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form action="index.php" method="POST" enctype="multipart/form-data">
                                    <label> File : </label>
                                    <input type="file" name="avatar" class="form-control">
                                    <button class="btn btn-primary float-end mt-2 mx-2" name="save" >ADD file</button>
                                    <button type="button" class="btn btn-secondary float-end mt-2 " data-bs-dismiss="modal">Close</button>
                                </form>
                            </div>
                          </div>
                        </div>
                      </div>
                          <p class="text-container">Add Story</p>
                     </div>
 
                     <?php foreach($all_user as $k=>$str): ?>
                         <?php  if($user->get_user_filter_friend($k,$_SESSION['idUser']) ||  $k==$_SESSION['idUser'] ): ?> 
                          <div class="<?= $k==$_SESSION['idUser'] ? 'content-myself' : 'content' ?>">  
                            <div class="img-container">
                                   <img data-bs-toggle="modal" data-bs-target="#exampleModal<?=$k?>" src="<?='../'.userFromId($k)['photo_user']?>" width="70px" height="70px" alt="img">
                             </div>
                              <p class="text-container"><?=userFromId($k)['name']?></p>
                              </div>
                         <?php  endif;?>
                     <div class="modal fade" id="exampleModal<?=$k?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                     <div class="modal-dialog">
                         <div class="modal-content">
                             <div class="modal-header">
                                 <h5 class="modal-title" id="exampleModalLabel"><?=userFromId($k)['name']?></h5>
                                 <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                             </div>
                                 <div class="all_story_for_user">
                                    <div class="modal-body mx-5" >
                                   
                                      <?php  foreach($str as $value ){ ?>
                                              <img class="slide" src="<?=$value['file']?>" width="70%" height="70%" alt="">     
                                      <?php  } ?>
                                      <?php // if( userFromId($k)['iduser']==$_SESSION['idUser']){?>
                                          <!--<a href="?idstory=?>"><button class="btn btn-danger">Delete cette story</button></a> -->
                                      <?php // } ?>
                                 
                                    </div>
                                </div>  
                      </div>
                  </div>
              </div>
            <?php endforeach; ?>
            </div>
          </div>
      <div class="container_post">
        <div class="wrapper">
          <section class="post">
            <p class="header">
               <span> Create Post</span>
            </p>
            <form action="index.php" method="POST" enctype="multipart/form-data">
              <div class="content">
                <img class="rounded" src="..<?=$_SESSION['avatarUser']?>" alt="logo">
                <div class="details">
                  <p><?=strtoupper($_SESSION['nameUser'])?></p>
                </div>
              </div>
           
              <textarea class="textarea" name="description" placeholder="What's on your mind ,<?=($_SESSION['nameUser'])?>"  required></textarea>
              <p>Theme :</p>
              <div class="theme d-flex justify-content-center mb-2">
          
                 <span class="color-circle color1">
                           
                  </span>
                  <span class="color-circle color2">
                      
                  </span>
                  <span class="color-circle color3">
                      
                  </span>
              </div>
              <input type="hidden" name="color_pub" id="color">
             
                 <input type="file" class="form-control w-50" name="avatar">
                 <div class="text-center mt-2">
                 <button name="add" class="btn btn-outline-primary">Post</button>
                 </div>
            </form>
          </section>
        </div>
      </div>
      <?php foreach($all_pub as $value): ?>
        <?php if($user->get_user_filter_friend($value['iduser'],$_SESSION['idUser']) ||  $value['iduser']==$_SESSION['idUser'] ): ?>
                <div class="feeds">
                    <div class="feed">
                        <div class="head">
                            <div class="user">
                                <div class="profile-photo">
                                       <img class="rounded" src="..<?=$value['photo_user']?>"  width="70px" height="70px" alt="">
                                </div>
                                <div class="ingo">
                                    <h3><?=$value['name']?></h3>
                                    <small><?=$value['date']?></small>
                                </div>
                            </div>
                            <?php if( $value['iduser']==$_SESSION['idUser'] ): ?>
                                <span class="edit">4<i class="fa-brands fa-github"></i></span>  
                            <?php endif; ?>
                        </div>     
                         <div class="decription mt-2 rounded" style="background-color:<?=$value['theme']!='' ? $value['theme'] : ''?>">
                             <?=$value['description']?>
                         </div>               
                        <?php if($value['avatar']!=''): ?>
                        <div class="photo">
                                <div>
                                    <img src="<?=$value['avatar']?>"   alt="">
                                </div>
                        </div>
                        <?php endif; ?>
                        <div class="action-button">
                            <div class="interraction-buttons">
                                <span>d<i class="fa-brands fa-github"></i></span>  
                                <span>d<i class="fa-brands fa-github"></i></span>  
                                <span>d<i class="fa-brands fa-github"></i></span>  
                            </div>
                            <div class="bookmark">
                                <span>d<i class="fa-brands fa-github"></i></span>  
                            </div>
                        </div>
                        <div class="liked-by">
                               <span><img src="..<?=$_SESSION['avatarUser']?>" width="70px" height="70px" alt=""></span>
                               <span><img src="..<?=$_SESSION['avatarUser']?>" width="70px" height="70px" alt=""></span>
                               <span><img src="..<?=$_SESSION['avatarUser']?>" width="70px" height="70px" alt=""></span>
                                 <p>Like by <b>talel mejri</b>and 2.23others</p>
                                 <p><b>Lana rose</b>hello ma maaaan</p>    
                        </div>
                        <div class="comments">
                             view all 277 comments
                        </div>
                    </div>
                    
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
    
    <script>

                let text=document.querySelector(".textarea");
                let color_changer=document.querySelector("#color");
                let color_circle=document.querySelectorAll('.color-circle');
                color_circle.forEach(color_current=>{
                 color_current.addEventListener('click',function(){
                    color_circle.forEach(color_choice=>{
                       color_choice.classList.remove('active');
                       this.classList.add('active');
                       color=this.classList +" ";
                       choice=color.substr(18,1);
                      if(choice==3){
                          color_changer.value="#2696E8";
                          color_changer.value="#2696E8";
                          text.style.backgroundColor="#2696E8";
                      }
                       else if(choice==2){
                          color_changer.value="#ff2d75";
                          color_changer.value="#ff2d75";
                          text.style.backgroundColor="#ff2d75";
                       }else if(choice==1){
                        color_changer.value="#fff";
                          color_changer.value="#fff";
                          text.style.backgroundColor="#fff";
                       }
                   })
                })
              })
             
let slideIndex = 0;
showSlides();

function showSlides() {
  let i;
  let slides = document.getElementsByClassName("slide");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}
  slides[slideIndex-1].style.display = "block";
  setTimeout(showSlides, 2000); 
}



</script>

