
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
  <thead>
     <tr>
        <th>id</th>
        <th>Name</th>
        <th>email</th>
     </tr>
     </thead>
       <?php if($all_user_filter=='vide'): ?>
        <tbody>
        <tr >
          <td colspan="3" class="text-center">Empty</td>
        </tr>
        <?php else: ?>
      <?php foreach($all_user_filter as $value): ?>
     <tbody>
        <tr>
          <td><?=$value['iduser']?></td>
          <td><?=$value['name']?></td>
          <td><?=$value['email']?></td>
     </tr>
     </tbody>
     <?php endforeach; ?>
 <?php endif; ?>
</table>