<div class="container d-flex justify-content-center align-items-center">
 <div class="col-md-5 py-5 ">
   <div class="card">
     <div class="card-header">
         <img width="100%" height="100%"  src="../../assets/image/90333-error.gif" alt="">
     </div>
     <div class="card-body text-center py-4">
            <div class="alert alert-danger">
                 <?=$errors[0]?> 
            </div>
            <a href="../login/"><button class="btn btn-outline-dark">Go BACK</button></a>
     </div>
 </div>
 </div>
</div>