<style>
    img{
        width: 50%;
        height: 50%;
    }
</style>
<div class="row">
<div class="col-md-3 text-center py-3">
        <img src="../../assets/image/124567-congrats.gif" alt="">
            </div>
         <div class="col-md-6 py-4 text-center">
              <h1 class="text-uppercase ">Congratulation <?=$name?>!</h1>
              Your email has already been confirmed.
               <p class="text-center">
                  <img src="../../assets/image/5242-check-orange.gif" alt="">
                </p>
                <p class="lead">You Can now login to the application After 5 Secondes </p>
        </div>
        <div class="col-md-3 text-center py-3">
                 <img src="../../assets/image/74659-confetti-day.gif" alt="">
        </div> 
  </div>
  </div>
  </div>
<script>
    setTimeout(()=>window.location.href="../login",5000);
</script>
 
           
             